#!/bin/sh
#
# Based on identibash

. ~/.dentrc

BASEURL="http://identi.ca/api/statuses"
FRIENDURL="$BASEURL/friends_timeline/${user}.rss"
#PUBLICURL="$BASEURL/public_timeline.rss"
UPDATEURL="$BASEURL/update.xml"
ITEMS=5
TMPFILE=~/.dent.tmp
HR="---"
EXCLUDE="$user and friends"

readmsg() {
#	clear
	curl -s $FRIENDURL > $TMPFILE
	COUNT=0
	echo $HR
	while read line; do
		if $(echo "${line}" | grep -v "$EXCLUDE" | grep -q "title>"); then
			echo "${line}" | sed 's/<title>//g' | sed 's/<\/title>//g'
		fi

		if $(echo "${line}" | grep -v "$EXCLUDE" | grep -q "pubDate>"); then
			echo "${line}" | sed 's/<pubDate>/on: /g' | sed 's/<\/pubDate>//g'
		fi

		if $(echo "${line}" | grep -q "</item>"); then
			echo $HR
			COUNT=$((COUNT + 1))
			if [ $COUNT -eq $ITEMS ]; then
				break
			fi
		fi
	done < $TMPFILE
}

postmsg() {
	curl -s -u ${user}:${pass} -d status="$MSG" ${UPDATEURL} 2>&1>/dev/null
}

getopts "arp:" OPT
case $OPT in
p)
	MSG=${OPTARG}
	postmsg
	;;
r)
	readmsg
	;;
esac
