#!/bin/sh

. ~/.dentrc

BASEURL="http://identi.ca/api/statuses"
FRIENDURL="$BASEURL/friends_timeline/$user.rss"
UPDATEURL="$BASEURL/update.xml"
ITEMS=5
TMPFILE=~/.dent.tmp
EXCLUDE="$user and friends"

crunch() {
	echo "$@" | tr -s ' ' | fmt -78
}

postmsg() {
	curl -s -u $user:$pass -d status="$MSG" $UPDATEURL 2>&1>/dev/null
}

readmsg() {
	curl -s $FRIENDURL > $TMPFILE
	COUNT=0
	echo '---'
	while read line; do
		if $(echo "${line}" | grep -v "$EXCLUDE" | grep -q "title>"); then
			crunch "${line}" | sed 's/<title>//g' | sed 's/<\/title>//g'
		fi

		if $(echo "${line}" | grep -v "$EXCLUDE" | grep -q "pubDate>"); then
			crunch "${line}" | sed 's/<pubDate>/on: /g' | sed 's/<\/pubDate>//g'
		fi

		if $(echo "${line}" | grep -q "</item>"); then
			echo '---'
			COUNT=$((COUNT + 1))
			if [ $COUNT -eq $ITEMS ]; then
				break
			fi
		fi
	done < $TMPFILE
}

getopts "p:r" OPT
case $OPT in
p)
	MSG=$OPTARG
	postmsg
	;;
r)
	readmsg
	rm -f $TMPFILE
	;;
esac
